### PR TITLE
#161028457 Feature create login page #finishes#161028457

### PR DESCRIPTION
**Pull request by Mukuria-Samuel**
# What does this PR do?
It Creates the login page for store_manager app users 
# Description of task to be completed?
Creation of the User Interface that would allow a user access the application by login.
# How should this be manually tested?
Clone my repository into your local machine, cd into it and open the user_login.html file with google chrome or a browser of your choice
# Any background context you want to provide?
None
# What are the relevant pivotal tracker stories?
#161028457
# Screenshots?
image

### CODE REVIEW

**Comment by boltonotieno** [comment]
You haven't attached a screenshot... would have been easier to comment on the UI design

**Comment by kwameasiago** [comment]
User Andela's naming convention when naming your branches hope this [link](https://github.com/andela/bestpractices/wiki/Git-naming-conventions-and-best-practices) will be helpful

**Comment by Mukuria-Samuel** [comment]
login page screen shot added to the #161028457 Feature create login page #finishes#161028457 PR

**Comment by Paulvitalis200** [comment]
Good design. But probably you can change the colour of the login button from red as the red normally denotes danger hehe.

**Pull request closed without merging**
